extra_css:
  - stylesheets/extra.css

site_name: Documentação SIGNO
site_description: Parâmetros para envio de atos por cartórios no sistema SIGNO
theme:
  name: material
  language: pt-BR
  logo: assets/cnb-sp.png
  favicon: assets/favicon.png
  palette:
    - scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Mudar para modo escuro
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro
  features:
    - navigation.sections
    - navigation.expand
    - search.highlight
    - navigation.top
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress

nav:
  - Home: index.md
  - CEP:
    - API: cep_api.md
    - Upload: cep_upload.md
    - Validadores:
        - CEP - API: validar_cep_api.md
  - CESDI:
    - API: cesdi_api.md
    - Upload: cesdi_upload.md
  - RCTO:
    - API: rcto_api.md
    - Upload: rcto_upload.md
  - Domínios Compartilhados: dominios.md

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true
      toc_depth: 4
extra_javascript:
  - javascripts/extra.js      